### ISSUE TITLE
Add support for generic PWM output node

### ISSUE THREAD

**Issue by rakeshpai** [mysensors/NodeManager#118]
...so that we can dim a light via NodeManager. :)

**Comment by user2684** [comment]
That's a good idea. Any sample sketch around I can take inspiration from? Thanks

**Comment by rakeshpai** [comment]
w00t! Thanks for considering this.

There are two examples in the MySensors examples set itself. A simple one [is here](https://github.com/mysensors/MySensors/blob/development/examples/DimmableLEDActuator/DimmableLEDActuator.ino). A second fancy one [is here](https://github.com/mysensors/MySensors/blob/development/examples/DimmableLight/DimmableLight.ino).

**Comment by user2684** [comment]
Cool thanks! Simple and clean example

**Comment by rakeshpai** [comment]
If I may add-on to this issue, could you also consider the ability to enable smooth transitions between levels when a level change is requested. The time for the transition could be configurable (default say 0.5s). 

What would be really awesome is if the transition function could be configurable too. [Here's a list of transition functions](http://easings.net/) commonly used in animations. Of course, we don't need to implement most of these functions. I would recommend just the first 4: Linear, easeInSine, easeOutSine, easeInOutSine. The ease* functions would really help in making the transitions feel natural, rather than the robotic linear transition function.

**Comment by user2684** [comment]
Cool idea, noted! Thanks

**Comment by user2684** [comment]
For my own reference: https://github.com/chicoplusplus/arduino/tree/master/libraries/Easing

**Comment by user2684** [comment]
Added SensorDimmer class, requiring MODULE_DIMMER which would unlock SENSOR_DIMMER. 
Implementation details in #192
