### ISSUE TITLE
DHT sensor is not working properly

### ISSUE THREAD

**Issue by user2684** [mysensors/NodeManager#170]
With both 1.5 and 1.6-dev
```
MY I=3 M=1
DHT I=2 T=nan
SLEEP 60s
```

**Comment by user2684** [comment]
Tested with DHT22 and it is working fine both temperature and humidity

**Comment by SergioRius** [comment]
Entire failing folder attached
[NodeManager_MultiSensor_v1.0.zip](https://github.com/mysensors/NodeManager/files/1152731/NodeManager_MultiSensor_v1.0.zip)

**Comment by user2684** [comment]
I'm experiencing a different issue but it may be related with #177. Investigation in progress

**Comment by user2684** [comment]
This should be fixed by #175. Looks like the MySensors's DHT library as you were suggesting works way better and fixes many issues. If the problem persists, feel free to re-open this issue
Thanks

**Comment by getlarge** [comment]
Could we keep the Adafruit DHT library for DHT21 and AM2305 (and maybe others) ?
The MySensors one does not work with AM2305...

**Comment by user2684** [comment]
DHT21 got lost while migrating to MySensors library, my mistake, sorry! I've added #196, the idea is to add a DHT21 specific module so to load the Adafruit's library just for this. Not great but I cannot think of a better compromise since a standard DHT sensor with the Adafruit's library has a lot of issues. Thanks for pointing this out!
