### ISSUE TITLE
Allow enabling internal pullup resistors

### ISSUE THREAD

**Issue by rakeshpai** [mysensors/NodeManager#186]
For simple switch-like sensors, like door sensors, switches, etc., we can enable the internal pullups in the microcontroller to avoid the use of external pullup resistors. It's easy to do (`pinMode(INPUT_PULLUP)`), and reduces component count.

[Example](https://github.com/mysensors/MySensorsArduinoExamples/blob/master/examples/BinarySwitchSensor/BinarySwitchSensor.ino#L52-L55) but this uses the old style.

**Comment by user2684** [comment]
Hi, there should be a setInitial() or equivalent function when having a pull up applies if I'm not wrong. Even if I'm not using INPUT_PULLUP but just INPUT followed by a DigitalWrite() it should be equivalent I guess. Am I wrong?
Thanks!

**Comment by rakeshpai** [comment]
Sorry, I didn't realise that setInitial was configuring the pullup resistors. PEBCAK - you have documented it correctly too. You might want to consider changing the name - I didn't associate the name with pullups. Closing this anyway - it certainly does what I need. Thanks!
