### ISSUE TITLE
Add support for DHT21 temperature and humidity sensor

### ISSUE THREAD

**Issue by user2684** [mysensors/NodeManager#196]
support got in and out with #175. Use Adafruit's library for this

**Comment by getlarge** [comment]
Well, it seems i got worried for nothing! I used DHT21 in Adafruit library to read the AM2305. But in fact it gets better reading with this library. so let's see with the real DHT21 (AM2301).

If it didn't, i thought of the same thing : create another module!

**Comment by user2684** [comment]
Oh cool, thanks, can I close this down then?

**Comment by getlarge** [comment]
Yes, but i would be probably be better to verify with a DHT21 (AM2301) owner that this lib works for them too ?

**Comment by user2684** [comment]
Good point. I'll keep this open until this will be tested (unfortunately I do not have such a sensor) but I'll change the milestone to v1.7. Thanks!
