### ISSUE TITLE
Problem with TSL2561 Module

### ISSUE THREAD

**Issue by betonmoewe** [mysensors/NodeManager#199]
I just try to get the TSL2561 Sensor (i2C) working, but without success! The nomal Arduino example scetch works perfect, but it seems, that the sensor would not be not initialized within nodemanager or something like that ...

Here my code:

int myTSL2561 = nodeManager.registerSensor(SENSOR_TSL2561);
((SensorTSL2561*)nodeManager.getSensor(myTSL2561))->setAddress(TSL2561_ADDR_FLOAT);
((SensorTSL2561*)nodeManager.getSensor(myTSL2561))->setGain(TSL2561_GAIN_16X);
((SensorTSL2561*)nodeManager.getSensor(myTSL2561))->setTiming(TSL2561_INTEGRATIONTIME_101MS);
((SensorTSL2561*)nodeManager.getSensor(myTSL2561))->setSpectrum(TSL2561_VISIBLE);
//nodeManager.registerSensor(SENSOR_BME280);

I also tried with only theregister line (nodeManager.registerSensor(SENSOR_TSL2561);), but the same. The BME280 works fine (if enabled).

what confuses me:

why is the constructor like that -> SensorTSL2561::SensorTSL2561(NodeManager* node_manager, int child_id): Sensor(node_manager, child_id,A2) ???

The TSL2561 is connected at A4,A5 because of i2c, but the constructor uses A2 ???

serial output:

REG I=1 P=16 P=16 T=37
NodeManager v1.6-dev
LIB V=2.1.1 R=N T=N A=A S=- B=-
INT P=3 M=255
INT P=2 M=255
RADIO OK
PRES I=200, T=23
PRES I=201, T=30
BATT V=3.45 P=100
SEND D=0 I=201 C=0 T=38 S= I=0 F=3.45
PRES I=1 T=16
READY

MY I=113 M=1
TSL I=1 L=19
SEND D=0 I=1 C=0 T=37 S= I=19 F=0.00
SLEEP 600s

**Comment by user2684** [comment]
https://forum.mysensors.org/topic/7266/nodemanager-v1-6-dev-comments-and-issues/4
