### ISSUE TITLE
setTrackLastValue does not work like expected ?

### ISSUE THREAD

**Issue by betonmoewe** [mysensors/NodeManager#204]
Hi

another problem:

I try to implement your setTrackLastValue method, but without success ...

Sleep time is 2 minutes
setTrackLastValue is set to true
setForceUpdateMinutes is set to 6.

I got my first reading, then 6 times only "awake  and sleep(120)" and then the next full reading. Between this 8 minutes, the reading (light / moisture) had certainly changed, but no message :(

or does I misunderstand the function?

Best regards

Frank

**Comment by betonmoewe** [comment]
forget it ... it seems, that there is a hardware problem ...

**Comment by user2684** [comment]
Ok, just in case the issue will show up again, feel free to re-open this ticket. Thanks!
