### ISSUE TITLE
ds18b20 and negative temperature values

### ISSUE THREAD

**Issue by fabix68** [mysensors/NodeManager#219]
I'm having problems with negative temperatures on a node with 2 ds18b20
if both sensors measure the positive temperature, the values ​​are correctly send. If one of the 2 negative negative values ​​is ignored.
everything works correctly using the example in the library.

**Comment by fabix68** [comment]
The error is in the NodeManager.cpp file in the section below here calculates the average of the detected values.

Exactly at this point
// process a float value
  else if (_value_type == TYPE_FLOAT **&& total > -1**)

**Comment by user2684** [comment]
Thanks. This is then a bigger issue then I thought since total is always initialized to -1 and in a few sections of the code this same logic is used. Fixing this requires initializing to a very low negative value and change all the comparisons. Good finding thanks.
