### ISSUE TITLE
S_WATER_LEAK sensor?

### ISSUE THREAD

**Issue by dakipro** [mysensors/NodeManager#220]
I think this is a basically a regular switch with interrupt, or am I wrong? 
I didn't find any example on the mysensors forum, few mentioned analog pins, but that is not a interrupt. Perhaps they wake up every 5min and check for sensor value?

Edit: I guess rain sensor is more appropriate ?

**Comment by user2684** [comment]
As far as I know those sensors are interrupt based. Usually there is a floating magnetic part and when there is a water leak goes up lift by the water and makes the interrupt trigger so the sensor will report a flood in progress. No analog pin is used as far as I know
