### ISSUE TITLE
Dev: Error compiling with 2.1.1 library (SR_RX_RSSI not declared in this scope)

### ISSUE THREAD

**Issue by user2684** [mysensors/NodeManager#256]
https://forum.mysensors.org/topic/6183/nodemanager-plugin-for-a-rapid-development-of-battery-powered-sensors/198

**Comment by enny1170** [comment]
I have the same issue, depending on the #define MY_SIGNAL_REPORT_ENABLED option

**Comment by user2684** [comment]
Thanks I'll fix this along the weekend

**Comment by user2684** [comment]
Fixed with bf9bfa7
