### ISSUE TITLE
Float precision for temperatures should default to 1 decimal place (enhancement)

### ISSUE THREAD

**Issue by liwenyip** [mysensors/NodeManager#270]
None of the commonly-used temperature sensors are accurate to more than +/- 0.3degC, so a temperature reading with 2 decimal places is meaningless.

I've implemented this in my fork of the master branch by calling  `setFloatPrecision(1);` in the constructor of `SensorDS18B20` and other temperature sensors; I can't find where float precision is handled in the development branch.

**Comment by liwenyip** [comment]
Yes, I think it's important to show a sensible number of decimal places for each sensor type by default. 

e.g.

- Battery voltage: 2 decimal places
- Temperature: 1 decimal place
- Humidity: 0 decimal places (or int)

This is because of the accuracy/precision of the sensors, and that more than 2 or 3 significant figures would be meaningless to most people, and can actually make the values harder to interpret. 

> I can make them global variables but they will not be per-sensor.
I wouldn't bother with this - if I want to change the precision globally, it's easy enough to change it where it's hard-coded.

**Comment by user2684** [comment]
For 0 decimal places ChildInt has to be used instead. The issue is related to ChildFloat only. Let me see if I can figure out a way to achieve this without changing too much code. Thanks!

**Comment by user2684** [comment]
Fixed through #305
