### ISSUE TITLE
SENSOR_SWITCH not recognised in home assistant

### ISSUE THREAD

**Issue by liwenyip** [mysensors/NodeManager#271]
SensorSwitch presents as S_CUSTOM with message type V_TRIPPED, which (it looks like) Home Assistant doesn't recognise.

Would it be more appropriate for SensorSwitch to present as S_BINARY/V_STATUS (which Home Assistant does recognise)?

Or is there a specific reason why it's presented as S_CUSTOM/V_TRIPPED?

**Comment by user2684** [comment]
Hi, I thought S_BINARY was more for relay type of sensor whereas the SensorSwitch class is for interrupt-based sensor like a PIR but probably you are right, regardless would be better to set the defaults to something which is recognized, I'll fix it. Meanwhile you can always customize it in your own code with something like sensorSwitch.children.get(1)->presentation = something, the same for type.
Thanks!

**Comment by liwenyip** [comment]
>  I thought S_BINARY was more for relay type of sensor

Actually you're right, S_BINARY appears in Home Assistant like this:

![image](https://user-images.githubusercontent.com/16456010/36066604-88f81ad4-0f00-11e8-83f5-ac03d9415f17.png)

So perhaps S_CUSTOM is more appropriate, but the message type would need to be V_CUSTOM for Home Assistant (and other controllers?) to recognise it.

**Comment by user2684** [comment]
Got it thanks, I'll use S_CUSTOM then. Maybe "SensorSwitch" is named in a wrong way, I'll see if it is worth renaming it entirely. Thanks!
