### ISSUE TITLE
SensorSwitch::onInterrupt() doesn't reliably detect rising/falling edge

### ISSUE THREAD

**Issue by liwenyip** [mysensors/NodeManager#273]
The issue is that there is a delay between the interrupt being triggered, and when this line of code executes:

https://github.com/mysensors/NodeManager/blob/4525b56f642d5996035f732a5a383ded59cdb9ed/NodeManagerLibrary.ino#L1549

The delay is typically 2ms if SERVICE_MESSAGES is not enabled, and 200-1500ms if SERVICE_MESSAGES is enabled. 

Say `_mode==FALLING`, and the pin receives a very brief pulse (e.g. a very brief push of a button); by the time this line of code runs the input may have gone high again, so `(_mode == FALLING && value == LOW)` will return false, and the method will interpret this as an invalid value.

My use case is a push button where I want to measure the length of time the button was pressed for. I've created a custom sensor that subclasses SensorSwitch; in the onInterrupt() method I need to be able to reliably tell whether the interrupt was triggered by a FALLING edge (button pushed) or a RISING edge (button released), even if the button was pushed so briefly that the pulse is only a few ms long. 

I believe the only reliable way to detect whether a CHANGE interrupt was triggered by a RISING or FALLING edge is to read the pin as the very first instruction in the ISR (and store it somewhere for later use). 

Apologies if that doesn't make sense (struggling with words today), happy to clarify if needed.

**Comment by user2684** [comment]
Very good point indeed. I should probably read store the value in the NodeManager's class like we do for _last_interrupt_pin just after the interrupt is triggered. I'll work on it, thanks.
PS. SERVICE_MESSAGES should be gone in the development branch
Thanks!
