### ISSUE TITLE
SensorDimmer cathod || anode

### ISSUE THREAD

**Issue by dudman8** [mysensors/NodeManager#297]
add function to class SensorDimmer to set cathod or anode driven LED... because I had to change
`analogWrite(_pin,value_to_write);`
to
`nalogWrite(_pin,255-value_to_write);` // add inversion here to handle cathod and anode leds`

**Comment by user2684** [comment]
Hi, thanks, makes sense, it will be part of v1.7

**Comment by dudman8** [comment]
Great thanks
