### ISSUE TITLE
Class instance misspelled APDS9960 (minor)

### ISSUE THREAD

**Issue by mitchmitchell** [mysensors/NodeManager#308]
Minor nit, but in going though the sensor list to see what was supported I noticed the following declaration: 
//SensorAPDS9960 apsd9960(node,3);

the DS and sd are swapped in the instance, the class name is correct the instance name is incorrect.

**Comment by user2684** [comment]
Thanks, will fix this asap

**Comment by user2684** [comment]
Fixed through #312
