### ISSUE TITLE
Add support for push button

### ISSUE THREAD

**Issue by user2684** [mysensors/NodeManager#316]
This be already implemented by using SensorInterrupt and can be linked to a relay by hooking into it. E.g.

```c
SensorInterrupt button(node,3);
SensorRelay relay(node,6);

void toggleRelay(Sensor* sensor) {
  relay.toggleStatus();
}

// before
void before() {
  // setup the serial port baud rate
  Serial.begin(MY_BAUD_RATE);
  
  button.setInterruptHook(&triggerRealy);
  button.setInitial(HIGH);
  button.setMode(FALLING);
}

```

**Comment by Pelado-Mat** [comment]
I need only a PUSHBUTTON and using an Sensor Interrupt is not working for me:
- The bounce2 library does a better job 
- The Child presentation must be V_STATUS and S_BINARY for HomeAssistant to work correctly.

Is there any chance to support this use case?

**Comment by user2684** [comment]
Hi, as for customizing the behaviour you can try with the following:
 
```
interrupt.children.get(1)-> setType(V_STATUS);
interrupt.children.get(1)-> setPresentation(S_BINARY);
```

As for bounce2, I'm sure it would do a better job but it requires storage and would have an overall impact also outside SensorInterrupt (which relies on NodeManager's interrupt handling capabilities). Which issues are you experiencing with the native debounce? Thanks!
