### ISSUE TITLE
SensorDs18b20::_getAddress(int index)  attempts to write into protected string constant on STM32

### ISSUE THREAD

**Issue by mitchmitchell** [mysensors/NodeManager#328]
I found out why the Ds18b20 routines were crashing on my HyTiny board and I *think* why they were working on the Arduino, apparently the STM32 has memory protection for string constants so using the statement char* charAddr = (char*)"                "; to allocate writeable string space doesn't work -- I'm guessing the Arduino processors don't and let you write into the constant.

I changed the statement to char* charAddr = new char[20]; and now the HyTiny is up and running and reporting temperature.   Now I see why it worked in the non-dev version and why I was seeing it work on the other boards.   

I'm not sure if new char[20] is the best way to allocate the storage but for now it has me back up and running.

**Comment by mitchmitchell** [comment]
Just discovered (should have known) the buffer needs to be blank or zero filled or you will get garbage at the end of the sensor string.

**Comment by user2684** [comment]
Thanks for reporting this issue. The address length is fixed so shouldn't be a problem allocating it in advance I'd say. How have you filled the buffer to avoid the garbage at the end? Whatever piece of code you can share would be helpful. Thanks!

**Comment by mitchmitchell** [comment]
Here is what I did:
  char* charAddr = new char[20];
  memset(charAddr,0x20,20);

**Comment by mitchmitchell** [comment]
You need to null terminate the address string as well:
around line 1783:
  }
  for (int j = 0; j < 16; j++) charAddr[j] = strAddr[j];
  **charAddr[16] = 0;**
  return charAddr;
}

**Comment by mitchmitchell** [comment]
or better to change the memset statement to:

  char* charAddr = new char[20];
  **memset(charAddr,0,20);**

no real reason to blank fill, just zero fill I guess.

**Comment by user2684** [comment]
Hi, would you mind giving PR #329 a try? Since the address is fixes 16 chars long, I've allocated an array 17 char length and then null terminate it. What do you think about it? thanks!

**Comment by mitchmitchell** [comment]
It works!   No problem with those changes.

**Comment by user2684** [comment]
Great thanks for the confirmation, I'm then going to merge the PR. Thanks!
