### ISSUE TITLE
Add support for GSM/SMS device

### ISSUE THREAD

**Issue by user2684** [mysensors/NodeManager#338]

**Comment by mitchmitchell** [comment]
I have a Hologram Nova Cellular IoT modem I could use to help test this if it is implemented.

**Comment by user2684** [comment]
Thanks I'll let you know once the development of this will start. It shouldn't be that difficult since everything is going through a serial connection and using AT commands. 
This is instead the device I will use for testing on my side out of curiosity:
https://www.aliexpress.com/item/Mini-A6-GA6-GPRS-GSM-Kit-Wireless-Extension-Module-Board-Quad-band-Antenna-Tested-Worldwide-Store/32843716737.html

**Comment by user2684** [comment]
Fixed by #429
