### ISSUE TITLE
LDR reverse not working

### ISSUE THREAD

**Issue by taltholtmann** [mysensors/NodeManager#346]
I have an LDR Sensor which is reporting the light level.
But  I cant get the reserve option to work. No matter if i set it to true/false. It´s always the same behaviour.

**Comment by user2684** [comment]
Hi, tagging this as a bug and adding to the 1.8 queue for further testing. Do you have any sample code to share? Thanks!

**Comment by user2684** [comment]
Double checking the code, both SensorLDR and SoilMoistureSensor calls setReverse() during onSetup(), this is why the behavior does not change unless called after node.setup(). I'm going to fix this by creating a variable to store this preference in the next version, thanks again for reporting this!

**Comment by user2684** [comment]
Fixed by #415
