### ISSUE TITLE
Implementing SensorVoltage?

### ISSUE THREAD

**Issue by nikolac** [mysensors/NodeManager#359]
I'm using SensorBattery to report my node's battery level, but I also have a small solar panel upstream of the battery that I want to report the voltage of separately. 

After considering using a generic AnalogInput, I realized that the SensorBattery has all of the code I would need. But, it has sendBatteryLevel embedded in it. 

Two thoughts: 1) make the sendBatteryLevel call conditional, based on an exposed configuration
2) Rename SensorBattery to SensorVoltage, remove the sendBatteryLevel calls. Create a new subclass of SensorVoltage called SensorBattery that includes the sendBatteryLevel.

**Comment by user2684** [comment]
I'd probably go with 1) by adding an option to allow the user to choose if reporting the voltage, the battery level of both. Adding to 1.8 queue. Thanks!

**Comment by user2684** [comment]
Fixed through #428
