### ISSUE TITLE
Issue with FEATURE_CONDITIONAL_REPORT with interrupt

### ISSUE THREAD

**Issue by Bottesford** [mysensors/NodeManager#420]
I have a battery powered node with a BH1750 sensor for which I have set conditional reporting as follows:

`light.children.get(1)->setValueDelta(2);
  light.children.get(1)->setForceUpdateMinutes(25);`

Attached to the same node I have a SensorDoor using interrupts. I had a problem when only rising changes were being sent back to the controller. The interrupt would fire and pre-post sleep messages would be sent but the actual payload:0 message would never be sent. If FEATURE_CONDITIONAL_REPORT was disabled it would work properly.

I tracked it down to _min_threshold var being set to FLT_MIN which comes up as 0. This meant the 0 value was being filtered out in the ChildInt::sendValue(bool force) method.
I set this in my node code:
`door.children.get(1)->setMinThreshold(-FLT_MIN);`
This resolves the issue. 
But probably that was not how this function was intended. Aware you are mid-way through a rewrite so maybe this doesn't apply any more but thought I'd point it out anyway as took some tracking down!

**Comment by user2684** [comment]
Thanks for reporting this issue, I've tagged as a bug and I'll try to reproduce it asap.

**Comment by user2684** [comment]
You're fully right, looks like FLT_MIN is the minimum (positive) float number. 
With #430 I've set it to -FLT_MAX (-FLT_MIN is always close to zero). 
I've also fixed a few other issues which came out while testing conditional reporting. 
Thanks!
