### ISSUE TITLE
Home Assistant connection

### ISSUE THREAD

**Issue by rspaargaren** [mysensors/NodeManager#436]
would it be possible to create a more easy connection with home assistant. The Hass requires that the sketch presents the values during startup in the loop.
For example for a relay:
  if (!initialValueSent) {
    Serial.println("Sending initial value");
    send(msg.set(state?RELAY_ON:RELAY_OFF));
    Serial.println("Requesting initial value from controller");
    request(CHILD_ID, V_STATUS);
    wait(2000, C_SET, V_STATUS);
  }

**Comment by user2684** [comment]
Good idea and I guess other controllers are expecting something similar. Adding it to the dev queue. This will not make it for the new upcoming version since almost ready and only bug fixes are accepted right now but for sure will be part of the future releases. Thanks

**Comment by RDG88** [comment]
Would like this one also!

**Comment by szurr** [comment]
hi i am trying to connect serial gateway and i only success with relay. should i register sensor in before? or something totaly diffrent

**Comment by user2684** [comment]
Hi @szurr is this related to this specific request or is it an unrelated general question? Thanks!

**Comment by szurr** [comment]
Above all thank you for this project.
 I guess that my problem with connecting sensors is related to presentation that Home assistant required. But guestion is Rather general.  Any chances for this enchantment in next release?

**Comment by user2684** [comment]
This should be fixed by #517 (see PR for implementation details) - both unit prefix and request initial value to the controller. Just keep in mind this is not the default so you need to add a few lines to your code. I'll keep this open until someone would confirm the implementation is ok. Thanks!

**Comment by szurr** [comment]
I'll try to check it. After I reinstall my dev home assistant

**Comment by szurr** [comment]
Sorry for my lack of understanding but  is hard coded request_initial_value parameter to true is enough? Or should I also set request in sensor class?(I am not quite sure where is it)😁

**Comment by user2684** [comment]
For the unit prefix, just call `nodeManager.setSendUnitPrefix(true)` (you can customize the prefix by calling `setUnitPrefix()` to the child).

For requesting initial value, you have to call `setRequestInitialValue(true)` to each child you want to request the initial value from the controller (since this makes sense only for a subset of sensors)

**Comment by szurr** [comment]
And I call for each child in presentation function?  I understand this that home assistant need presentation of every sensor at boot and then only changes of state. So I figured that this is only needed at beginning. Are there somewhere any examples where to put those calls?
Edit 
I try to attached sensor to serial gateway via USB for testing maybe this is my problem that this is not nodes connected to gateway Wich is only relay information

**Comment by user2684** [comment]
Correct, call it on every child but do it in before() (e.g. where the NodeManager code is usually located, have a look at Template.ino for examples). Keep also in mind this feature does not change what NodeManager does in presentation: every child is always presented to the controller, regardless of these settings. Thanks

**Comment by szurr** [comment]
hi thanks for update
first comment was off i make misake the correct example for one relay is:
 // call NodeManager before routine
  nodeManager.before();
  relay.children.get(51)->setRequestInitialValue(true);


and i can't add sensor door and motion to be visible in home assistant i try in many setup  
cheers

Edit
About multiple sensors:
 I found that to add multiple sensors I needed to ad number  eg
SensorRelay relay1(4);
SensorRelay relay2(5);
SensorRelay relay3(6);
Thanks user 2684 it was in your post on mysensors forum

**Comment by user2684** [comment]
Sorry my bad, forgot to mention, ensure you are using code from PR #517 (e.g. https://github.com/user2684/NodeManager/tree/fix/core) otherwise you cannot use the new functionalities. This is because this PR has not been merged yet. Thanks

**Comment by user2684** [comment]
Also ensure to configure any sensor *before* calling nodeManager.before(). As for SensorRelay, yes of course you need to configure it with a different pin number for each sensor. Thanks

**Comment by user2684** [comment]
#517 has been merged into development so I'm going to close this issue. Feel free to reopen it again if needed
