### ISSUE TITLE
sleepBetweenSend actually waitBetweenSend?

### ISSUE THREAD

**Issue by nikolac** [mysensors/NodeManager#456]
I'm trying to run a few nodes off of super-capacitors and I'm seeing higher than expected voltage drops after transmission. I thought increasing sleepBetweenSend would help, but longer wait was causing bigger drop. 

I noticed that wait() is called instead of sleepOrWait() or sleep(). Is there a reason not to call sleep if the gap is large enough, more than ~500ms?

**Comment by user2684** [comment]
Hi, Thanks for reporting this. The behavior of sleepBetweenSend() has been changed with v1.8 because of #405 (ack was lost while sleeping). I'll see if this can be better customized in the next release. Thanks!

**Comment by user2684** [comment]
Fixed by #517. Added` setSleepBetweenSendSleepOrWait()` to customize the behavior
