### ISSUE TITLE
HyTiny board does not have pin PB8

### ISSUE THREAD

**Issue by mitchmitchell** [mysensors/NodeManager#461]
In Constants.h the definition of INTERRUPT_PIN_1 fails when compiling for the HyTiny boad because there is no PB8 pin on the HyTiny.

I do not yet know what pin to recommend for the HyTiny board as I am unclear why PB8 specifically is used on the STM32 processors -- I will have to research that.

// define interrupt pins

#if defined(CHIP_STM32)
#define INTERRUPT_PIN_1 PB8
#define INTERRUPT_PIN_2 2
#else
#define INTERRUPT_PIN_1 3
#define INTERRUPT_PIN_2 2
#endif

**Comment by user2684** [comment]
Fixed by #512
I removed entirely the define for CHIP_STM32 so now users can for any board define their own INTERRUPT_PIN_1  and INTERRUPT_PIN_2
