### ISSUE TITLE
use of MY_ESP8266_SSID and MY_ESP8266_PASSWORD deprecated

### ISSUE THREAD

**Issue by mitchmitchell** [mysensors/NodeManager#466]
Compiling the template .ino file configured as an ESP8266 gateway warns that the two #defines for specifying the SSID and Password for the WiFi network are deprecated and compilation fails.

#define MY_ESP8266_SSID "myssid"
#define MY_ESP8266_PASSWORD "mypassword"

 #warning MY_ESP8266_SSID is deprecated, use MY_WIFI_SSID instead!

  ^

C:\Users\Mitch.MAGNOLIAMANOR\Documents\Arduino\libraries\MySensors/core/MyGatewayTransportMQTTClient.cpp:33:2: warning: #warning MY_ESP8266_PASSWORD is deprecated, use MY_WIFI_PASSWORD instead! [-Wcpp]

 #warning MY_ESP8266_PASSWORD is deprecated, use MY_WIFI_PASSWORD instead!

**Comment by user2684** [comment]
You're right, this has changed somewhere between 2.2 and 2.3 and needs to be fixed in the template as well

**Comment by user2684** [comment]
Fixed by #512
