### ISSUE TITLE
Values not presenting in DisplaySSD1306

### ISSUE THREAD

**Issue by user2684** [mysensors/NodeManager#469]
https://forum.mysensors.org/topic/10145/values-not-presenting-in-displayssd1306

**Comment by ElCheekytico** [comment]
I have a motion sensor, DHT22, and DisplaySSD1306 connected. I am experiencing the same issue. The values are read from the sensors and sent to the controller. However, the display shows lines for battery, DHT22 temp and humidity, and motion, but they are showing 0 for values.
![IMG_20190407_171405](https://user-images.githubusercontent.com/9792166/55689951-2ccb6780-5959-11e9-96ba-a82d17db5122.jpg)

**Comment by user2684** [comment]
Thanks, can you also share your sketch as well?

**Comment by ElCheekytico** [comment]
[TempHumMotionDisplayBatteryNode.txt](https://github.com/mysensors/NodeManager/files/3060218/TempHumMotionDisplayBatteryNode.txt)

**Comment by ElCheekytico** [comment]
Any luck with this? Anything I can do to help move this along?

**Comment by user2684** [comment]
Hi, development for the new version has not started yet and unfortunately I'm short of spare time to speed this up :-( For sure will put my effort on this issue as the first thing (https://github.com/mysensors/NodeManager/projects/3) but feel free to submit a PR for this if you like. Thanks!

**Comment by ElCheekytico** [comment]
Any luck figuring this out?

**Comment by user2684** [comment]
Hi, still not on this, sorry. I'm waiting to line up enough issues to start organizing the new development

**Comment by ElCheekytico** [comment]
Any progress yet?

**Comment by user2684** [comment]
Not yet, really sorry and this has been open for more than a year now so you are completely right in asking for progress...hope this lockdown can help in starting the new development cycle which has still to start. Thanks

**Comment by user2684** [comment]
Hi, the root cause of this resulted the same of #433 hence have been just fixed (in the development branch) in #511
