### ISSUE TITLE
Compiler Warnings indicating problems!

### ISSUE THREAD

**Issue by g0uus** [mysensors/NodeManager#472]
Hi,
I just downloaded and installed the latest zip version and attempted a build of the AnalogLightAndTemperatureSensor example using Arduino IDE 1.8.8.
I always build with the Compiler Warnings = All setting (as I do in my day job!)
This produces a few warnings that, on investigation are real code issues.

    C:\Users\grh\Google Drive\Arduino\libraries\NodeManager-master/nodemanager/Node.cpp: In member function 'void NodeManager::before()':
    C:\Users\grh\Google Drive\Arduino\libraries\NodeManager-master/nodemanager/Node.cpp:163:18: warning: comparison is always true due to limited range of data type [-Wtype-limits]
      if (_reboot_pin > -1) {
                      ^
    
    In file included from C:\Users\grh\Google Drive\Arduino\libraries\NodeManager-master/MySensors_NodeManager.h:82:0,
                     from C:\Users\grh\Google Drive\Arduino\libraries\NodeManager-master\examples\AnalogLightAndTemperatureSensor\AnalogLightAndTemperatureSensor.ino:58:
    C:\Users\grh\Google Drive\Arduino\libraries\NodeManager-master/nodemanager/Node.cpp: In member function 'void NodeManager::reboot()':
    C:\Users\grh\Google Drive\Arduino\libraries\NodeManager-master/nodemanager/Node.cpp:351:19: warning: comparison is always true due to limited range of data type [-Wtype-limits]
       if (_reboot_pin > -1) {
                       ^
   
    C:\Users\grh\Google Drive\Arduino\libraries\NodeManager-master/nodemanager/Node.cpp: In member function 'void NodeManager::_setupInterrupts()':
    C:\Users\grh\Google Drive\Arduino\libraries\NodeManager-master/nodemanager/Node.cpp:484:28: warning: comparison is always true due to limited range of data type [-Wtype-limits]
       if (_sleep_interrupt_pin > -1) {
                                ^
   
    C:\Users\grh\Google Drive\Arduino\libraries\NodeManager-master/nodemanager/Node.cpp: In member function 'void NodeManager::setAnalogReference(uint8_t, uint8_t)':
    C:\Users\grh\Google Drive\Arduino\libraries\NodeManager-master/nodemanager/Node.cpp:743:10: warning: comparison is always true due to limited range of data type [-Wtype-limits]
      if (pin > -1) {
              ^

In each case these are caused because the `*_pin` variable is declared as `uint8_t` which, by definition, can never be less than zero, hence the code protected by the is statement will ALWAYS be executed.

If all `pin` values are always declared as `uint8_t`, and there can never be a pin 255, the simplest fix is probably to declare `constexpr uint8_t NO_PIN = 255` and replacing all the uses of `-1` (where it means "no pin" with `NO_PIN`

Graham

**Comment by user2684** [comment]
Thanks a lot for reporting this! Tagged as a bug and will be fixed in the next release
Thanks again!

**Comment by user2684** [comment]
Fixed by #512. This was actually a big issue. Fix was by initializing those variables to 0 (since pin 0 is never valid) so to keep data type
