### ISSUE TITLE
TTP sensor not working

### ISSUE THREAD

**Issue by Bottesford** [mysensors/NodeManager#483]
I am using the TTP226 and found it was only sending a value to the controller once after first boot. After that no further touches would be sent to the controller. 
I found in the fetchData() function in SensorTTP that the 'ziro' variable is never reset to 0 at the end of the function. This left it getting higher and higher each call so the pad would never transmit a value again. Setting ziro = 0 got the pad working as expected.

**Comment by user2684** [comment]
Thanks, good finding, marking it as a bug

**Comment by user2684** [comment]
Fixed by #514
