### ISSUE TITLE
Multiple samples averaging error

### ISSUE THREAD

**Issue by nielbierman** [mysensors/NodeManager#501]
I have found that when requesting more than one read to average by using setSamples(), the reading being sent is always the last reading and not the average of the samples.
The value sent in the attached example was 213...the last of the 30 values read. The average is actually 209.6
![Annotation 2020-02-03 192648](https://user-images.githubusercontent.com/20477014/73676138-8527de80-46bc-11ea-8e15-8b72a7299b1a.png)

**Comment by user2684** [comment]
Thanks for reporting this! I tag it as a bug and fix in the next release

**Comment by user2684** [comment]
After reviewing the code, this looks like related to the way values are processed for each child when per-child processing policies have been introduced. The default is to keep the latest value only, this is why your sampling is not working. Try calling setValueProcessing(AVG) to the child object and let me know. Thanks!
