### ISSUE TITLE
Issues compiling for NRF5x

### ISSUE THREAD

**Issue by user2684** [mysensors/NodeManager#503]
Ref. https://forum.mysensors.org/topic/10315/nrf5x-on-nodemanager

**Comment by spREGR** [comment]
Hi, 
I changed the radio define line for the NRF5x. And normally, we are required to have two tabs containing MyBoardNRF5.cpp and MyBoardNRF5.h along with the .ino file when compiling for this board. Getting the following errors


[error.txt](https://github.com/mysensors/NodeManager/files/4498459/error.txt)

[Template.zip](https://github.com/mysensors/NodeManager/files/4498455/Template.zip)

**Comment by user2684** [comment]
Thanks, I was finally able to reproduce the problem. Looks like the issue is related to the newest version of the MySensors library. Give a try with 2.3.1 instead of 2.3.2, to me compiled just fine. If confirmed of course I urgently need to support 2.3.2 as well since looks like something has changed under the hood making it not fully compatible with NodeManager. Thanks!

**Comment by spREGR** [comment]
Hi, Yes, it compiles with 2.3.1...but there is no output on the serial monitor and nothing on the MQTT traffic as well. 
[nodemanagertest_lib2.3.1.zip](https://github.com/mysensors/NodeManager/files/4539029/nodemanagertest_lib2.3.1.zip)

**Comment by user2684** [comment]
Ok, at least this is a step ahead, unfortunately fixing compilation issues is way easier than reproducing runtime issues :-) Let me try setting up a test board and see if I can get somewhere. Do you have any *working* code to share (just mysensors, without NodeManager) for this board so I can try to find the differences. Thx

**Comment by user2684** [comment]
Nevermind, I was eventually able to reproduce it but unfortunately not fixing it. As you may have noticed, the problem is not in the serial output but looks like a runtime error is making the sketch crashing hence no output is returned. I spent long time trying to isolate the problem and the first candidate is NodeManager's debug() which is mapping directly MySensors HwDebugPrint(). The latter is used by MySensors core without issues but when I call it (actually whenever I use a Serial.print), there is apparently a crash. I couldn't find an explanation yet and debugging it could be time consuming. If I could only get some sort of stack trace from the board upon crash....

**Comment by spREGR** [comment]
If there is something that you need me to try or do ; let me know

**Comment by user2684** [comment]
Just if you have a better way for testing rather than flashing with st-linkv2, disconnecting, connecting  to a serial TTL and run it since it is very time consuming going through this process to verify a single line commented out is making it crashing or not. Is there a way to flash and connect to serial like a standard arduino board without using two different USB devices? Thanks

Unfortunately it is very manual and try-and-error the process with this since I have no clue what is making it crashing at runtime and need to debug line per line :-/

**Comment by user2684** [comment]
This should be fixed by #512 :-) (issue related to #463)
