### ISSUE TITLE
Request Max and Min Range for all sensors

### ISSUE THREAD

**Issue by iamyourexpert** [mysensors/NodeManager#518]
Is it possible to have a max and min for a sensor. I did see analog sensors has that feature. Would be nice have for all
```
void setRangeMin(int value);
 void setRangeMax(int value);
````

**Comment by user2684** [comment]
Hi, I've just closed as duplicated #513 which seems to be the same. Have a look at `NODEMANAGER_CONDITIONAL_REPORT` and specifically `setMinThreshold()` and `setMaxThreshold() `which should do what you are looking for. If not, feel free to reopen this ticket. Thanks
