### ISSUE TITLE
Debug prints wrong floating point numbers

### ISSUE THREAD

**Issue by j54n1n** [mysensors/NodeManager#542]
Hello there,

I noticed when NODEMANAGER_DEBUG and NODEMANAGER_DEBUG_VERBOSE are enabled that floating point numbers get printed in a wrong fashion probably due to some overflow.

For example if I set the value of a sensor to 32767.6789 I get following log:
```
5313 NM:LOOP:TEST(202):SET t=48 v=32767.-32
5317 NM:MSG:SEND(202) t=48 p=32767.04
5330 TSF:MSG:SEND,84-84-0-0,s=202,c=1,t=48,pt=7,l=5,sg=0,ft=0,st=OK:32767.68
``` 
This happens both with DOUBLE and FLOAT formats. But as you can see the line from MySensors is showing correctly the truncated and rounded value. So at the end it is only a cosmetic error.

I will try to fix it with an pull request shortly.

Kind regards.

**Comment by user2684** [comment]
Thanks, my understanding is that the right value is sent over the network BUT the way it is printed is wrong. Thanks a lot for the PR, will merge straight away!
