### ISSUE TITLE
Use time library to keep track of the current time after requesting it

### ISSUE THREAD

**Issue by user2684** [mysensors/NodeManager#83]
http://playground.arduino.cc/Code/time

**Comment by getlarge** [comment]
Any progress on this one? You want to save time on a RTC ?
Based upon the time aware sensor sketch, i made a routine in which the time of the controller is transmitted to the node at the init. When the message is received, it synchronizes with internal timer of the arduino and with the RTC. And in case time from controller can't be received, we use the RTC time.
This part was related to the scheduler i told you about.

**Comment by user2684** [comment]
This will be pretty complex to put in place, I'm still figuring out the most simple and effective way. Good idea to use a RTC module, it would avoid asking the controller continuously. 
I'm also looking for a library which can be installed if possible directly from the arduino ide so to be consistent with the other dependencies. Thanks

**Comment by jsiddall** [comment]
I will also vote for this one.  I am not even that interested in using an RTC, just in being able to keep track of the ToD.  All that should be required for that is a periodic, and ideally configurable (ex: hourly), call to requestTime() and then simply calling setTime(ts) to receiveTime() to keep the clock in sync.

I believe the crystal in the Arduinos has a tolerance of 0.5% which is less than a minute per hour of drift.

**Comment by user2684** [comment]
I've started working on it recently, keep on eye on #259 while it progresses. Thanks
