### ISSUE TITLE
Expose BME/BMP advanced settings

### ISSUE THREAD

**Issue by user2684** [mysensors/NodeManager#89]
E.g. power-modes, filtering and oversampling

**Comment by user2684** [comment]
Not sure if accessible for all BME/BMP libraries, postponing

**Comment by jasonmhite** [comment]
It's all accessible in the Adafruit lib, they even have constants for the different modes defined. Look at the public methods for `Adafruit_BME280`.

https://github.com/adafruit/Adafruit_BME280_Library/blob/master/Adafruit_BME280.h#L127

**Comment by user2684** [comment]
Thanks! getting this back into the v1.8 queue

**Comment by user2684** [comment]
Added setSampling() to BME280 only (the other BME/BMP sensors do not expose such a method) through #413,
