### ISSUE TITLE
Add capability to show data on a LCD

### ISSUE THREAD

**Issue by user2684** [mysensors/NodeManager#95]
This would depend in #93 with a global lcd object in NM and the other sensors accessing it plus a global routine

**Comment by bilbolodz** [comment]
Maybe better is to use i2c connected LCD and implement "general use" something like MySensors to I2C bridge? Just idea maybe stupid.

**Comment by user2684** [comment]
It is a good idea indeed, I should also have a i2d LCD somewhere to test. I need to structure a good generic use case so to have NM managing the LCD without the user to necessarily do it in a different way for every sensor. Thanks

**Comment by user2684** [comment]
Also add a S_INFO child so text can be set also remotely

**Comment by user2684** [comment]
This feature must be LCD-related, closing it but referring implementation to #281 and #280
