### ISSUE TITLE
Pulse Sensor

### ISSUE THREAD

**Issue by Shagrat2** [mysensors/NodeManager#96]
Append pulse sensor

Power Meter Pulse Sensor
Water Meter Pulse Sensor

**Comment by user2684** [comment]
Good one!
I'll take https://www.mysensors.org/build/pulse_power and https://www.mysensors.org/build/pulse_water as examples to build those sensors into NodeManager. Thanks

**Comment by user2684** [comment]
Bought the following, waiting for delivery:
* https://www.aliexpress.com/item/Photosensitive-Sensor-Module-Light-Detection-Module-for-Arduino/1886288541.html?spm=2114.13010608.0.0.pVTs5l
* https://www.aliexpress.com/item/free-shipping-TCRT5000-infrared-reflectance-sensor-Obstacle-avoidance-module-tracing-sensor-tracing-module/32214044656.html?spm=2114.13010608.0.0.pVTs5l

**Comment by user2684** [comment]
Done, implementation details on #194
