### ISSUE TITLE
Add a function to turn ADC off

### ISSUE THREAD

**Issue by Shagrat2** [mysensors/NodeManager#97]
If not use ADC insert this code. Save 0.2 mA
Please check on your devices

```
  // Disable the ADC by setting the ADEN bit (bit 7) to zero.
  ADCSRA = ADCSRA & B01111111;
  
  // Disable the analog comparator by setting the ACD bit
  // (bit 7) to one.
  ACSR = B10000000;
```

**Comment by user2684** [comment]
Interesting, 0.2mA is a lot. I'll add a function to enable/disable the ADC. Do you have by chance also the code for enabling it back?
Thanks

**Comment by Shagrat2** [comment]
Please check on your devices

http://forum.arduino.cc/index.php?topic=78430.0
