### ISSUE TITLE
Changing node id remotely doesn't work

### ISSUE THREAD

**Issue by user2684** [mysensors/NodeManager#98]
I had to remove the include of MyHwAVR.h since creating problems between versions hence hwWriteConfig() cannot be called

**Comment by getlarge** [comment]
That might be related to Mysensors lib update? Hardware files have been removed to hal directory.

**Comment by user2684** [comment]
Correct, I used to include MyHwAVR.h to execute hwWriteConfig() but I preferred to avoid it even if it is still there in the HAL directory now otherwise I need to find a way to include a different file based on the lib version and it is quite a mess. Additionally if possible I prefer not using internal functions which can be changed at any time. Still I need to figure out how to solve it in a different way :)

**Comment by user2684** [comment]
Closing this since I don't think it would be reliable to change the node id on the fly and would require hw-specific hwWriteConfig() to be called (https://github.com/mysensors/MySensors/blob/af3452f91c15b60cc7666b6225fa7342f08a6f52/core/MyTransport.cpp#L126)
